name: User Story
description: Sprint-sized work
type: user-story
body:
  - type: input
    id: parent_feature
    attributes:
      label: Parent Feature
      description: "Type # to search and select a feature"
      placeholder: "#456"
  - type: textarea
    id: story
    attributes:
      label: Story
      description: As a [role], I want [capability], so that [benefit]
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - Criterion 1
        - Criterion 2
    validations:
      required: true
  - type: dropdown
    id: points
    attributes:
      label: Points
      options: ["1","2","3","5","8","13"]
